services:
  pos-controle-frontend:
    image: ghcr.io/sidneyjfg/pos-controle-frontend:latest
    container_name: pos-controle-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3002}:3002"
    networks:
      - pos-controle

networks:
  pos-controle:
    name: pos-controle
    external: true
